name: Deploy

on:
  push:
    tags:
    - '*'

jobs:
  cocoapods:
    name: Cocoapods
    needs: tests
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Push podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push